name       : haskell-basement
version    : 0.0.7
release    : 1
source     :
    - https://hackage.haskell.org/package/basement-0.0.7/basement-0.0.7.tar.gz : b501b9b378f35b80c60321031dbbf9ed7af46c66353f072e00f00abdd2244f70
license    : BSD-3-Clause
component  : programming.haskell
summary    : Foundation most basic primitives without any dependencies
description: |
    Foundation most basic primitives without any dependencies
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
