name       : haskell-basement
version    : 0.0.11
release    : 2
source     :
    - https://hackage.haskell.org/package/basement-0.0.11/basement-0.0.11.tar.gz : 67582b3475a5547925399f719df21f8bbbd0ca4d4db27795c22a474f8ee6346b
license    : BSD-3-Clause
component  : programming.haskell
summary    : Foundation most basic primitives without any dependencies
description: |
    Foundation most basic primitives without any dependencies
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
